name: Alexisreport
version: 0.3.1
main: fr.alexis.report.Main
commands:
  report:
  die:
    usage: /command
  setbutton:
    description: Sets the location of the button
    usage: /setbutton
  oldreport:
    description: test
  help:
    description: une commande help je vois pas d'autres choix ;-; ?